### ISSUE TITLE
CMakeLists, Line 344. tlx directory does not exist

### ISSUE THREAD

**Issue by aaditya2200** [wheatman/concurrent-btrees#3]

**Comment by wheatman** [comment]
sorry, the layout of this code is a little confusing since it was just a branch of of the tlx repo.
We do not have support for cmake.  All the code we add is header only code for the different containers.

the btree_tests directory has the driver code which can show you how to use the code.

the code itself for the bp-tree can be found at https://github.com/wheatman/concurrent-btrees/blob/merged_code/tlx-leafds/container/btree.hpp 

the basic concurrent btree used as a reference can be found at https://github.com/wheatman/concurrent-btrees/blob/merged_code/tlx-plain/container/btree.hpp

sorry for the confusion

**Comment by aaditya2200** [comment]
Got it. I just changed the tlx to tlx-plain and cmake worked. Thank you.

**Comment by wheatman** [comment]
so just to be clear, tlx-plain is not the bp-tree it is a concurrent b+-tree that we used as a reference implementation

**Comment by aaditya2200** [comment]
got it
